### ISSUE TITLE
undeclared name: kiotaazure

### ISSUE THREAD

**Issue by sivan-koren** [microsoft/kiota-authentication-azure-go#43]
The readme gives this example:
```
cred, err := azidentity.NewDeviceCodeCredential(nil)
authProvider, err := kiotaazure.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"User.Read"})
```

This seems to assume that kiotaazure is part of this package: github.com/Azure/azure-sdk-for-go/sdk/azidentity

Is it?

**Comment by baywet** [comment]
Thanks for reporting this gap in the documentation. Authored #44 to address it.
